---
apiVersion: v1
kind: Service
metadata:
  name: alloy-nodeport
  labels:
    app.kubernetes.io/name: alloy
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: alloy
  ports:
  - name: metrics
    port: 12345
    targetPort: 12345
    protocol: TCP
    nodePort: 31234
  - name: grpc-tempo-otlp
    port: 4317
    protocol: TCP
    targetPort: 4317
    nodePort: 30317
  - name: http-tempo-otlp
    port: 4318
    protocol: TCP
    targetPort: 4318
    nodePort: 30318
