---
apiVersion: v1
kind: Service
metadata:
  name: loki-nodeport
  labels:
    app.kubernetes.io/name: loki
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "3100"
spec:
  type: NodePort
  ports:
  - name: http-metrics
    port: 3100
    protocol: TCP
    targetPort: http-metrics
    nodePort: 30310
  selector:
    app.kubernetes.io/name: loki
