---
apiVersion: v1
kind: Service
metadata:
  name: mimir-nodeport
  labels:
    app.kubernetes.io/name: mimir
spec:
  type: NodePort
  ports:
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 30808
  - name: grpc
    port: 9095
    targetPort: 9095
    nodePort: 30095
  selector:
    app.kubernetes.io/name: mimir
